// pragma solidity ^0.4.2;

// import "truffle/Assert.sol";
// import "truffle/DeployedAddresses.sol";
// import "../contracts/Ferro.sol";

// contract TestFerro {

//   function testInitialBalanceUsingDeployedContract() {
//     Ferro( ferro = Ferro(DeployedAddresses.Ferro());

//     uint expected = 10000;

//     Assert.equal(ferro.balanceOf(tx.origin), expected, "Owner should have 10000 Ferro initially");
//   }

//   function testInitialBalanceWithNewFerro() {
//     Ferro ferro = new Ferro();

//     uint expected = 10000;

//     Assert.equal(ferro.balanceOf(tx.origin), expected, "Owner should have 10000 Ferro initially");
//   }

// }
